apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guildnet-deviceparticipant-writer
rules:
  - apiGroups: ["guildnet.io"]
    resources: ["deviceparticipants"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["guildnet.io"]
    resources: ["deviceparticipants/status"]
    verbs: ["get", "update", "patch"]
