apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-demo
  labels:
    app: agent-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-demo
  template:
    metadata:
      labels:
        app: agent-demo
    spec:
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: agent
          image: codercom/code-server:4.90.3
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"
            - name: AGENT_TLS_SELF_SIGNED
              value: "1"
            # Optional hint for UI when node hostname is not available in API payload
            # Set to the Kubernetes Service DNS name or Pod IP as appropriate
            - name: AGENT_HOST
              value: "agent-demo"
            # OPTIONAL: set PASSWORD explicitly; code-server also supports /home/coder/.config/code-server/config.yaml
            #- name: PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: agent-demo-secret
            #      key: PASSWORD
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
              ephemeral-storage: "4Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "8Gi"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: workspace
              mountPath: /workspace
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: agent-demo-data
        - name: workspace
          persistentVolumeClaim:
            claimName: agent-demo-workspace
---
apiVersion: v1
kind: Service
metadata:
  name: agent-demo
  labels:
    app: agent-demo
spec:
  selector:
    app: agent-demo
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 8443
      targetPort: https

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-demo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: <your-storage-class>  # Uncomment to pin a non-default class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-demo-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  # storageClassName: <your-storage-class>  # Uncomment to pin a non-default class
