apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-demo
  labels:
    app: agent-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-demo
  template:
    metadata:
      labels:
        app: agent-demo
    spec:
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
        fsGroup: 10001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: agent
          image: ghcr.io/hexafield/guildnet-agent:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"
            - name: AGENT_HOST
              value: "agent-demo"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
              ephemeral-storage: "8Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
              ephemeral-storage: "16Gi"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: workspace
              mountPath: /workspace
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 20Gi
        - name: workspace
          emptyDir:
            sizeLimit: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: agent-demo
  labels:
    app: agent-demo
spec:
  selector:
    app: agent-demo
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 8443
      targetPort: https